# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-11 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_remove_answer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tag title'),
        ),
    ]
