# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-11 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_auto_20170411_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ask.Tag', verbose_name='Tags'),
        ),
    ]
