# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-11 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_auto_20170411_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'', verbose_name='Avatar'),
        ),
    ]
