# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-11 14:53
from __future__ import unicode_literals

import ask.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=ask.models.avatar_dir_path, verbose_name='Avatar'),
        ),
    ]
