# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-11 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_auto_20170411_1453'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ask',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create date'),
        ),
        migrations.AddField(
            model_name='ask',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create date'),
        ),
        migrations.AddField(
            model_name='uservote',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create date'),
        ),
    ]
