# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-22 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0008_auto_20170503_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correnct',
            field=models.BooleanField(default=False, verbose_name='Correct answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(verbose_name='Answers'),
        ),
    ]
