# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-22 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0009_auto_20170522_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='is_correnct',
            new_name='is_correct',
        ),
    ]
